appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: EYj/sNEdO6xBeX2UKo5pqLDpkBPPwu8WPEC5j88W8QoDKBI4R+5bQaQbEi1Bmmijm68OfsC6dM2GeKdv/DzOZ2vFFLQG7MDjyMAv318i6RJnc2M7BFuHm2ftQxBJpTiEZf4BBGZf6Urgka6dxz37jglc824MX0ECz1/UfhwacVSQ51CMOQSG8ODu0q4+MUAHz3eJfqNflSjDSER4GEKsw3J9ASEe9N/Jt1cMLhVl8N/Rsyo6velXXSewZQ3kA9OAXAEpAWe95c6TaM+aiKeqQyANjooaJLzYjN2tGZrWTeSWiILnte3L/avy0vDAeLADKi9SNAe7v3WS750vpEHGEioUvdkotLPCL9HkpQIChcyevi1txUI6VLRMFv0wJ6wYuazqkkiWmn9RwQ3Yal6coy6pidQDPqjxHjNOSu4fbh8ibzp+M1EoCNpr4IUsSxRWcazZDa9yKjy1QCKwzr8RMRPCn/3i3Cm3oFNWUN/99w8Rw3TzN3Q3WRr6QNAPMy4vVxpiU7FGqMaebkdU4anJdj33zZEMFNefuRQyVx+wrFgX1rPAX9jtBqw3QE33BURalQibXKZr/chMeb7UAORfxTJIm1Ukd2O/xQW61YxkYBT3l21gLpn8qcc3pO/l9t37PmSzahONWXQ4PkPPN940qGcerb718DoxXDxTyKAZPhU=}
bot:
  automerge: true
