travis:
  secure:
    BINSTAR_TOKEN: ZRUKBS98GzKg6KokQFi6i5EiGzeu+8YfM2KzBC6Kj0Mkjm6Wj0Tf4SQFX2zdCXFEHIjHGwdzTq85oPFSaytNYfqAtarNq0ZN/2sIeeoEh1AkiGMupENJibJhp7MDrDAgF7+g5zFhtrnO+30AtuIDyvVeLIeHmXSjOfp1mJr0V7wtGIRItmklhzadzcXI/9x3HBAXIc2s/PO3UzdJI/ppSxTKvOW2CrYsgfikzWaVFcZMcJ7BbJhCXW/CqDHkCWjyO6V7PN7pfIRuiqNm2LS0fzTQIMPpg7Hy7/S3/oZVuMqSTBPunrkZM2mt6fv2Z/++Y5ZwJEE8czkI3AQ77LrklkIJmuj2l/UTJjSD1+m78Ov1yjvnDB3uIz2wEa62JydHHmTgADc7akQ/SSnepR+AndI+4bezVN+5ogbYuW63cLQLlBcVPgvVsCJIOHi/rp4Z1PBNnkTNbXDBtZV9a+AOTJdRpqETrBZrU/BDsxBXysrnckMh3vxzqAVeOV6VfgmEewrXM1n9RwFVzI/AmfQXb8hPEpTURjbookdMtwLBGvB+UJ0x/Zz0cNDO4deDYoi0gvGoTe8IXzplK5ZMrGZmc5gIU1cwGenm7kcnJ7+8sYC34rkgcWzW/1Gd+P+Ac3bOKKPiIiBs215gLdB+OJiUyQUnj3WyWDuR1MoVA0kgEWw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
